from src.graph_url.workflow import build_graph

ARTICLE_URLS = [
    "https://en.wikipedia.org/wiki/Ziraat_Bank",
    "https://en.wikipedia.org/wiki/Halkbank",
    "https://en.wikipedia.org/wiki/Vak%C4%B1fBank",
    "https://en.wikipedia.org/wiki/T%C3%BCrkiye_Kalk%C4%B1nma_Bankas%C4%B1",
    "https://en.wikipedia.org/w/index.php?title=T%C3%BCrk_Eximbank&action=edit&redlink=1",
    "https://en.wikipedia.org/wiki/%C4%B0ller_Bankas%C4%B1",
    "https://en.wikipedia.org/wiki/Central_Bank_of_the_Republic_of_Turkey",
    "https://en.wikipedia.org/wiki/Turkish_State_Railways",
    "https://en.wikipedia.org/wiki/BOTA%C5%9E",
    "https://en.wikipedia.org/wiki/TPAO",
    "https://en.wikipedia.org/wiki/Eti_Mine_Works",
    "https://en.wikipedia.org/wiki/Turkish_Hard_Coal_Enterprises",
    "https://en.wikipedia.org/wiki/PTT_(Turkey)",
    "https://en.wikipedia.org/wiki/TOK%C4%B0",
    "https://en.wikipedia.org/wiki/Mechanical_and_Chemical_Industry_Corporation",
    "https://en.wikipedia.org/wiki/Aselsan",
    "https://en.wikipedia.org/wiki/HAVELSAN",
    "https://en.wikipedia.org/wiki/Turkish_Aerospace_Industries",
    "https://en.wikipedia.org/wiki/Roketsan",
    "https://en.wikipedia.org/wiki/ASFAT",
    "https://en.wikipedia.org/wiki/T%C3%BCrksat_(company)",
    "https://en.wikipedia.org/wiki/%C3%87aykur",
    "https://tr.wikipedia.org/wiki/Alarko_Holding",
    "https://tr.wikipedia.org/wiki/Anadolu_Efes",
    "https://tr.wikipedia.org/wiki/Anadolu_Isuzu",
    "https://tr.wikipedia.org/wiki/Ar%C3%A7elik",
    "https://tr.wikipedia.org/wiki/ASELSAN",
    "https://tr.wikipedia.org/wiki/Aygaz",
    "https://tr.wikipedia.org/wiki/Baykar",
    "https://tr.wikipedia.org/wiki/Beko",
    "https://tr.wikipedia.org/wiki/B%C4%B0M",
    "https://tr.wikipedia.org/wiki/BMC_(T%C3%BCrkiye)",
    "https://tr.wikipedia.org/wiki/Borusan",
    "https://tr.wikipedia.org/wiki/BOTA%C5%9E",
    "https://tr.wikipedia.org/wiki/Cengiz_Holding",
    "https://tr.wikipedia.org/wiki/%C3%87ukurova_Holding",
    "https://tr.wikipedia.org/wiki/DenizBank",
    "https://tr.wikipedia.org/wiki/Do%C4%9Fan_Holding",
    "https://tr.wikipedia.org/wiki/Do%C4%9Fu%C5%9F_Holding",
    "https://tr.wikipedia.org/wiki/Eczac%C4%B1ba%C5%9F%C4%B1_Holding",
    "https://tr.wikipedia.org/wiki/Enka_%C4%B0n%C5%9Faat",
    "https://tr.wikipedia.org/wiki/Erdemir",
    "https://tr.wikipedia.org/wiki/Eti_Maden",
    "https://tr.wikipedia.org/wiki/Fibabanka",
    "https://tr.wikipedia.org/wiki/QNB_Bank",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Garanti_Bankas%C4%B1",
    "https://tr.wikipedia.org/wiki/HAVELSAN",
    "https://tr.wikipedia.org/wiki/Ko%C3%A7_Holding",
    "https://tr.wikipedia.org/wiki/LC_Waikiki",
    "https://tr.wikipedia.org/wiki/Migros_T%C3%BCrk",
    "https://tr.wikipedia.org/wiki/Nurol_Holding",
    "https://tr.wikipedia.org/wiki/OPET",
    "https://tr.wikipedia.org/wiki/Otokar",
    "https://tr.wikipedia.org/wiki/Ford_Otosan",
    "https://tr.wikipedia.org/wiki/Oyak_Renault",
    "https://tr.wikipedia.org/wiki/Petkim",
    "https://tr.wikipedia.org/wiki/Petrol_Ofisi",
    "https://tr.wikipedia.org/wiki/PTT_(T%C3%BCrkiye)",
    "https://tr.wikipedia.org/wiki/Roketsan",
    "https://tr.wikipedia.org/wiki/Sabanc%C4%B1_Holding",
    "https://tr.wikipedia.org/wiki/TAI",
    "https://tr.wikipedia.org/wiki/Turkcell",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_Hava_Yollar%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_Telekom",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_%C4%B0%C5%9F_Bankas%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Petrolleri",
    "https://tr.wikipedia.org/wiki/T%C3%9CPRA%C5%9E",
    "https://tr.wikipedia.org/wiki/T%C3%9CRKSAT",
    "https://tr.wikipedia.org/wiki/Vestel",
    "https://tr.wikipedia.org/wiki/Yap%C4%B1_ve_Kredi_Bankas%C4%B1",
    "https://tr.wikipedia.org/wiki/Y%C4%B1ld%C4%B1z_Holding",
    "https://tr.wikipedia.org/wiki/Ziraat_Bankas%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_B%C3%BCy%C3%BCk_Millet_Meclisi",
    "https://tr.wikipedia.org/wiki/Cumhurba%C5%9Fkanl%C4%B1%C4%9F%C4%B1_(T%C3%BCrkiye)",
    "https://tr.wikipedia.org/wiki/Anayasa_Mahkemesi",
    "https://tr.wikipedia.org/wiki/Yarg%C4%B1tay",
    "https://tr.wikipedia.org/wiki/Dan%C4%B1%C5%9Ftay",
    "https://tr.wikipedia.org/wiki/Say%C4%B1%C5%9Ftay",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Cumhuriyet_Merkez_Bankas%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_%C4%B0statistik_Kurumu",
    "https://tr.wikipedia.org/wiki/Afet_ve_Acil_Durum_Y%C3%B6netimi_Ba%C5%9Fkanl%C4%B1%C4%9F%C4%B1",
    "https://tr.wikipedia.org/wiki/Gelir_%C4%B0daresi_Ba%C5%9Fkanl%C4%B1%C4%9F%C4%B1",
    "https://tr.wikipedia.org/wiki/Sosyal_G%C3%BCvenlik_Kurumu",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_%C4%B0%C5%9F_Kurumu",
    "https://tr.wikipedia.org/wiki/Karayollar%C4%B1_Genel_M%C3%BCd%C3%BCrl%C3%BC%C4%9F%C3%BC",
    "https://tr.wikipedia.org/wiki/Devlet_Su_%C4%B0%C5%9Fleri",
    "https://tr.wikipedia.org/wiki/Tapu_ve_Kadastro_Genel_M%C3%BCd%C3%BCrl%C3%BC%C4%9F%C3%BC",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_Patent_ve_Marka_Kurumu",
    "https://tr.wikipedia.org/wiki/T%C3%9CB%C4%B0TAK",
    "https://tr.wikipedia.org/wiki/T%C3%9CRKAK",
    "https://tr.wikipedia.org/wiki/T%C4%B0KA",
    "https://tr.wikipedia.org/wiki/Vak%C4%B1flar_Genel_M%C3%BCd%C3%BCrl%C3%BC%C4%9F%C3%BC",
    "https://tr.wikipedia.org/wiki/Mill%C3%AE_%C4%B0stihbarat_Te%C5%9Fkilat%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_E%C4%9Fitim_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Diyanet_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_Silahli_Kuvvetlerini_G%C3%BC%C3%A7lendirme_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/Vehbi_Ko%C3%A7_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/Sabanc%C4%B1_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/TEMA_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/Ensar_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/L%C3%B6semili_%C3%87ocuklar_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Maarif_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/T%C3%BCrkiye_Ekonomik_ve_Sosyal_Et%C3%BCdler_Vakf%C4%B1",
    "https://tr.wikipedia.org/wiki/Orta_Do%C4%9Fu_Teknik_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/%C4%B0stanbul_Teknik_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Bo%C4%9Fazi%C3%A7i_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Hacettepe_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Bilkent_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/%C4%B0stanbul_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Ankara_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Gazi_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/Ege_%C3%9Cniversitesi",
    "https://tr.wikipedia.org/wiki/An%C4%B1tkabir",
    "https://tr.wikipedia.org/wiki/Topkap%C4%B1_Saray%C4%B1",
    "https://tr.wikipedia.org/wiki/Ayasofya",
    "https://tr.wikipedia.org/wiki/T%C3%BCrk_ve_%C4%B0slam_Eserleri_M%C3%BCzesi",
    "https://tr.wikipedia.org/wiki/Anadolu_Medeniyetleri_M%C3%BCzesi",


]

def main():
    print("Starting data collection from url pipeline...")

    app = build_graph()

    result = app.invoke({
        "article_urls": ARTICLE_URLS,

        "errors": [],

        "enable_raw_qa": False,

        # testing limits
        "max_chunks_per_article": 100,
        "max_nuggets_per_chunk": 4,
        "max_nuggets_per_article": 400,
    }) 

    print("Errors:", result.get("errors"))
    print("Data collection from url pipeline finished.")


if __name__ == "__main__":
    main()
